### ISSUE TITLE
legaltext_url Templatetag

### ISSUE THREAD

**Issue by stephrdev** [moccu/django-legaltext#18]
Add a template tag which acts like url tag including support for "as" which takes the internal slug of a legal text and returns the url based on slug or url name - depending on available data.

**Comment by lenarother** [comment]
What is the "internal slug"? Could it be solved by setting custom url, like in https://github.com/moccu/loreal-perfectageclub/blob/master/src/perfectage/urls.py#L60?

**Comment by lenarother** [comment]
Fixed with 48cc400
